### edit event by id
PUT http://localhost:8080/events/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc2MjgzNTM5MiwiZXhwIjoxNzYyOTIxNzkyfQ.19KNWq8vWg1FQ6LiHyHQKRO4lyphLaSTeqCm2Dozeq8

{
    "id": 1,
	"title": "title goes here 2",
	"description": "description goes here",
	"imageUrl": "imge url to s3 bucket",
	"videoUrl": "videoUrl.com link to s3 bucket"
}
