### get user by username
GET http://localhost:8080/users/johnl
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc2MjgzNTM5MiwiZXhwIjoxNzYyOTIxNzkyfQ.19KNWq8vWg1FQ6LiHyHQKRO4lyphLaSTeqCm2Dozeq8