spring.datasource.url=jdbc:postgresql://${SUPABASE_DB_HOST}:5432/${SUPABASE_DB_NAME}?sslmode=require
spring.datasource.username=${SUPABASE_DB_USER}
spring.datasource.password=${SUPABASE_DB_PASSWORD}

spring.flyway.enabled=true
spring.flyway.default-schema=public
spring.flyway.locations=classpath:db/migration

supabase.url=https://${SUPABASE_DB_HOST}
supabase.key=${SUPABASE_SECRET_KEY}
supabase.bucket=${SUPABASE_BUCKET}
supabase.url.expiry=3600