name: Terraform + Backend CI/CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_BUCKET: starry-night-media
      EC2_USER: ubuntu
      BACKEND_JAR_NAME: fullstack-1.0-SNAPSHOT.jar

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build backend
        run: mvn clean package -DskipTests

      - name: Upload artifact to S3
        run: aws s3 cp target/${{ env.BACKEND_JAR_NAME }} s3://${{ env.S3_BUCKET }}/${{ env.BACKEND_JAR_NAME }} --region ${{ env.AWS_REGION }}

  deploy-infra:
    runs-on: ubuntu-latest
    needs: deploy

    defaults:
      run:
        working-directory: ./infra

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra

      - name: Import existing S3 bucket
        run: terraform state list | grep aws_s3_bucket.media_bucket || terraform import aws_s3_bucket.media_bucket starry-night-media

      - name: Import existing resources
        run: terraform state list | grep aws_iam_role.ec2_role || terraform import aws_iam_role.ec2_role backend-ec2-role-tf \
              && terraform state list | grep aws_security_group.backend_sg || terraform import aws_security_group.backend_sg sg-0bc0052f2f186e2f3

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./infra
